In [ ]:
import pandas as pd
#將csv直接轉換成dataframe
DataFrame1 = pd.read_csv('各鄉鎮市區人口密度.csv')
DataFrame1

In [3]:
#取出columns,index
DataFrame1.index
DataFrame1.columns

Index(['statistic_yyy', 'site_id', 'people_total', 'area',
       'population_density'],
      dtype='object')

In [6]:
#改變欄位名稱
DataFrame1.columns = ['統計年','區域別','年底人口數','土地面積','人口密度']

DataFrame1

,統計年,區域別,年底人口數,土地面積,人口密度
0,統計年,區域別,年底人口數,土地面積,人口密度
1,111,新北市板橋區,549572,23.1373,23753
2,111,新北市三重區,379825,16.317,23278
3,111,新北市中和區,403109,20.144,20011
4,111,新北市永和區,212170,5.7138,37133
...,...,...,...,...,...
370,111,南沙群島,…,0.5045,…
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN

In [9]:
#使用pandas.dataframe.drop()直接刪除列或reindex()適合選取特定列,刪除資料
dataframe2 = DataFrame1.drop(index=0)
dataframe2

,統計年,區域別,年底人口數,土地面積,人口密度
1,111,新北市板橋區,549572,23.1373,23753
2,111,新北市三重區,379825,16.317,23278
3,111,新北市中和區,403109,20.144,20011
4,111,新北市永和區,212170,5.7138,37133
5,111,新北市新莊區,419966,19.7383,21277
...,...,...,...,...,...
370,111,南沙群島,…,0.5045,…
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN

In [13]:
DataFrame1.reindex(index=[1,2,3,4,5])

   統計年     區域別   年底人口數     土地面積    人口密度
1  111  新北市板橋區  549572  23.1373  23753
2  111  新北市三重區  379825   16.317  23278
3  111  新北市中和區  403109   20.144  20011
4  111  新北市永和區  212170   5.7138  37133
5  111  新北市新莊區  419966  19.7383  21277

In [18]:
dataframe2.iloc[-10:]#查看倒數5行
dataframe3 = dataframe2.reindex(index=range(1,371))
#用reindex(index=range(?,?)存取我們要的列數

In [19]:
dataframe3

     統計年     區域別   年底人口數     土地面積    人口密度
1    111  新北市板橋區  549572  23.1373  23753
2    111  新北市三重區  379825   16.317  23278
3    111  新北市中和區  403109   20.144  20011
4    111  新北市永和區  212170   5.7138  37133
5    111  新北市新莊區  419966  19.7383  21277
..   ...     ...     ...      ...     ...
366  111  連江縣北竿鄉    3181      9.9    321
367  111  連江縣莒光鄉    1471      4.7    313
368  111  連江縣東引鄉    1534      3.8    404
369  111    東沙群島      …      2.38      …
370  111    南沙群島      …    0.5045      …

[370 rows x 5 columns]

In [21]:
#選取留存所要的欄位
dataframe4 = dataframe3.reindex(columns=['區域別','年底人口數','土地面積','人口密度'])
dataframe4

        區域別   年底人口數     土地面積    人口密度
1    新北市板橋區  549572  23.1373  23753
2    新北市三重區  379825   16.317  23278
3    新北市中和區  403109   20.144  20011
4    新北市永和區  212170   5.7138  37133
5    新北市新莊區  419966  19.7383  21277
..      ...     ...      ...     ...
366  連江縣北竿鄉    3181      9.9    321
367  連江縣莒光鄉    1471      4.7    313
368  連江縣東引鄉    1534      3.8    404
369    東沙群島      …      2.38      …
370    南沙群島      …    0.5045      …

[370 rows x 4 columns]

In [25]:
dataframe5 = dataframe4.drop(columns=['區域別'])
dataframe5

         年底人口數     土地面積    人口密度
區域別
新北市板橋區  549572  23.1373  23753
新北市三重區  379825   16.317  23278
新北市中和區  403109   20.144  20011
新北市永和區  212170   5.7138  37133
新北市新莊區  419966  19.7383  21277
...        ...      ...     ...
連江縣北竿鄉    3181      9.9    321
連江縣莒光鄉    1471      4.7    313
連江縣東引鄉    1534      3.8    404
東沙群島        …      2.38      …
南沙群島        …    0.5045      …

[370 rows x 3 columns]

In [26]:
dataframe5.loc[['新北市三重區','新北市永和區','新北市板橋區']]

         年底人口數     土地面積    人口密度
區域別
新北市三重區  379825   16.317  23278
新北市永和區  212170   5.7138  37133
新北市板橋區  549572  23.1373  23753